const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT';
const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
const CART_SAVE_PAYMETN ='CART_SAVE_PAYMETN';

export {CART_ADD_PRODUCT, CART_REMOVE_PRODUCT, CART_SAVE_SHIPPING, CART_SAVE_PAYMETN};