const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

const PRODUCT_ITEM_REQUESTED = 'PRODUCT_ITEM_REQUESTED';
const PRODUCT_ITEM_SUCCESS = 'PRODUCT_ITEM_SUCCESS';
const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL';

const PRODUCT_SAVE_REQUESTED = 'PRODUCT_SAVE_REQUESTED';
const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

const PRODUCT_DELETE_REQUESTED = 'PRODUCT_DELETE_REQUESTED';
const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';


export {PRODUCT_LIST_REQUESTED,PRODUCT_LIST_SUCCESS,PRODUCT_LIST_FAIL};
export {PRODUCT_ITEM_REQUESTED,PRODUCT_ITEM_SUCCESS, PRODUCT_ITEM_FAIL};
export {PRODUCT_SAVE_SUCCESS,PRODUCT_SAVE_REQUESTED,PRODUCT_SAVE_FAIL};
export {PRODUCT_DELETE_SUCCESS,PRODUCT_DELETE_REQUESTED,PRODUCT_DELETE_FAIL};